### ISSUE TITLE
Bug:Not Working on 22000.1

### ISSUE THREAD

**Issue by gailium119** [valinet/Win11DisableRoundedCorners#1]
When using on 22000.1 ,the program says pattern not found

**Comment by valinet** [comment]
Yeah, probably, as the pattern that I look for is not there in that form. Basically, what this program does is it patches the following function from `uDWM.dll` which is responsible for telling the application the radius for the window corners: `CTopLevelWindow::GetEffectiveCornerStyle`. If it returns 0, that means the corners will be basically squared, so the same appearance from Windows 10 is achieved. Now, maybe the function does not terminate the same way in 22000.1 as it does in newer versions. I suggest opening `uDWM.dll` from 22000.1 in IDA or something similar, and then inserting the opcodes for `xor rax, rax` somewhere near the method return. That's a cold patch right there, the same thing this patcher utility does automatically.

**Comment by valinet** [comment]
Probably fixed in latest build, 1.0.0.2.

**Comment by gailium119** [comment]
thanks,thougb i did it manually

**Comment by gailium119** [comment]
is there a way to crack the verion limit o installing uwp apps? i managed to locate appxdeploymentclient.dll,but i can't know which function to hook

**Comment by gailium119** [comment]
it's useful since the limit of microsoft store is 22000.20,not 22000.1

**Comment by valinet** [comment]
Yeah, I know what you are saying... Stupid limitation, I encountered it as well, 22000.1 is too Windows 10-ish so they wanted everyone on .51 or newer. Look on the symbol list for `appxdeploymentclient.dll`, find if something in there seems of interest. I am not familiar with this framework, haven't looked on that DLL.

Do you know how to dump symbols for a DLL? Basically, use either IDA Freeware to disassemble the whole binary, or [PDB Downloader](https://github.com/rajkumar-rangaraj/PDB-Downloader) and then [pdbdump](https://gist.github.com/phaufe/2973037).

**Comment by gailium119** [comment]
I dumped the symbols but i don't know which function

**Comment by gailium119** [comment]
[Microsoft.Windows.Appx.PackageManager.Commands.zip](https://github.com/valinet/Win11DisableRoundedCorners/files/7278290/Microsoft.Windows.Appx.PackageManager.Commands.zip)
this the source code of the appx module of powershell i decompiled

**Comment by valinet** [comment]
> 
> 
> I dumped the symbols but i don't know which function

I don't know either, I also don't work at Microsoft, most of the stuff I start from a "don't know" state, attempt some things, sometimes basically following a strategy, sometimes randomly, observe the results and sometimes hit something useful. Hook some functions that seem interesting, see when it gets there, what it does, and so on... I can't tell you the exact symbol to hook, as I simply don't know it either. We (or I) don't even know if that is the right DLL to look into... it takes more than 5 minutes to investigate this...

> 
> 
> [Microsoft.Windows.Appx.PackageManager.Commands.zip](https://github.com/valinet/Win11DisableRoundedCorners/files/7278290/Microsoft.Windows.Appx.PackageManager.Commands.zip) this the source code of the appx module of powershell i decompiled

I don't think the actual logic for deploying the package is in the cmdlet. But I don't know much on the topic either. Attach some debugger, try to see for yourself, I also don't have unlimited free time, I am a bit busy at work at the moment, try to do some comprehensive investigation and report back what your findings are, please. Thanks.

**Comment by gailium119** [comment]
the cmdlet just provides translation of user-input and fuction prototypes; the real functions are native , in the dll

**Comment by valinet** [comment]
Makes sense.

**Comment by valinet** [comment]
There is also `AppXDeploymentServer.dll`. Isn't that a more likely place for the check to actually happen? I don't know, just saying... 

Why stay on 22000.1 anyway, just curious...?

**Comment by gailium119** [comment]
with explorerpatcher and start_showclassicmode nobody will discover it's win11

**Comment by gailium119** [comment]
![image](https://user-images.githubusercontent.com/77530553/135867285-65f404cd-1435-4b87-b810-734f140bf51a.png)
because it's in the reference list

**Comment by gailium119** [comment]
the decompiling took me a whole day and it's a bit late for me now

**Comment by valinet** [comment]
> 
> 
> ![image](https://user-images.githubusercontent.com/77530553/135867285-65f404cd-1435-4b87-b810-734f140bf51a.png) because it's in the reference list

Yeah, but maybe the 'client' just talks with the 'server' and asks that to deploy the package. The client may be as much as the cmdlet is, just further passing on commands to the server. Idk.

> 
> 
> the decompiling took me a whole day and it's a bit late for me now

A whole day to do the autoanalysis in IDA or what? It should take nowhere near that...

> 
> 
> with explorerpatcher and start_showclassicmode nobody will discover it's win11

Yeah, the Windows 10 Start menu, I understand. Well, it works on newer builds as well, only thing is, there are some small bugs around it, I was writing this mail a couple of days ago to someone asking the same question, here is what I said on the topic, maybe you find it useful:

Original enquiry: would it be possible to add an option to bring back the Windows 10 Start menu? It was possible with Windows 11 22000.51 with the Start_ShowClassicMode regentry. In the StartMenuExpierenceHost.exe there was an Existence check that was Looking for it.

My reply:
Indeed, I looked on it, the code is still there. Well, most of it is intact. Most of it. The thing is, it does not work properly. In the brief time that I run and looked at it, there are at least 2/3 issues:

* Right clicking any item crashes the Start menu
* There is a delay of 1-2 seconds when the desktop does not update after the Start menu is dismissed (I know, weird)
* Live tiles seem kind of broken - they act weird, changing often but not really updating the information displayed

Of course, I looked on the disassembly as well; the check for the registry entry has been replaced with basically a call to a function called "IsPPIEnabled" (I don't know what "PPI" stands for in this context). That function boils down to checking whether the edition reported by "GetProductInfo" is 119 (or 0x77). If it is, it returns 1, otherwise 0. That number is nowhere to be found in the documentation, so I don't know what Windows version it refers to, but maybe I missed something. I tested and confirmed that, indeed, if you make "IsPPIEnabled" return 1 (or patch the IAT to have "GetProductInfo" provide a Windows version with number 119), the Windows 10 Start menu shows in all its glory, but with the issues mentioned above. Now, there are two ways to achieve this:

* The way I did it, was to modify the return of "IsPPIEnabled" (modify the "rax" register after the call) using a debugger (I used WinDbg)
* Alternatively, use a "StartMenuExperienceHost.exe" from an older build (like .51, for example). You can also try with a "StartDocked.dll" from that build as well ("StartDocked.dll" is what hosts the logic for the menu, apparently)

The problems occur regardless if using files from the latest build or from .51, so clearly something else this depends on changed. I don't know. Maybe you can investigate this, starting from this pointers that I gave you.

Also, regarding enabling this automatically using ExplorerPatcher, a funny thing happened: that check is so early in the execution, that by the time "dxgi.dll" gets injected, the program has long ago decided to use the new menu, so my in-memory patching is useless. "dxgi.dll" works better for File Explorer as that calls very early one of the DXGI functions. So yeah, even hooking this is pretty hard. Hooking may have to be done substituting another DLL, avoiding KnownDLLs (list is in "HKML\SYSTEM\CurrentControlSet\Control\Session Manager\KnownDLLs") etc.

So yeah, that's the story so far. And that's the story in general with Windows 11. Not only do they remove features, but they also break them just a bit to make them not work well if enabled back somehow. For example, for Win+X in ExplorerPatcher, I leveraged a lot of code from their DLLs - they just removed the code in the actual method that showed the menu, so I had to port that over from an older version of the DLL ("twinui.pcshell.dll").

I will maybe look more into it some day if I have time, but I can't make any promises; I don't know. With a few fixes, the new menu is fine as well, matches the aesthetic with search, can be centered and so on. They should just add officially some common sense options, like the ones from my patcher, plus things like resizing the menu, pining a few icons in the app list etc., then it is all fine by me.

Anyway, good luck with this, maybe you find a solution or someone else who can also help a bit with the matter as well.

**Comment by gailium119** [comment]
basically powershell modules are .net dlls,so use dotpeek or dnspy instead of ida(ida will damage the signature and make the dll no longer function), and the better way is to decompiling it into a c# project and rebuild it in visual studio(and sign it with my own signature).The problem is, dlls involving uwp runtimes have a situation rard to decompile automatically.eg....the = operatior will be understood as this.put_(nameoffunction) and i have to change them one by one;also the refferences are hard to restore due to version mismatched of sdks.

**Comment by gailium119** [comment]
as for ppi , i assume it is short of ppipro,a.k.a windows.team, a version of windows different from home and pro.If you are interested you can get the iso from uupdump.net by choosing windows.team.However,it must be tested in virtual machines since installation will alter the esp partion making the normal system unbootable.

**Comment by gailium119** [comment]
Also the settings in 22000.1 is more win10 style

**Comment by valinet** [comment]
Okay, so Windows Team presumably has the old menu still enabled even in 22000.194? I am curious actually, I am downloading an ISO right now and will check in a VM.

**Comment by valinet** [comment]
Yeah, Team is locked down version of Windows for the Surface Hub, and, indeed, the Windows 10 Start menu is used there. Nothing has been updated for it, it uses the same UI from Windows 10, with square window corners and so on. So yeah, probably you're right, that check is there to help enable the old UI on that version only. But, as I said, one can override that, yet on the regular desktop, the Windows 10 Start menu has a few issues, so not really useful... or maybe someone fixes those, finds what the root cause of that is, idk.

**Comment by gailium119** [comment]
i think i've got a solution with the new store. adding appx packages with dism /add-provisionedappxpage instead of powershell somehow bypasses the limit.

**Comment by valinet** [comment]
> 
> 
> i think i've got a solution with the new store. adding appx packages with dism /add-provisionedappxpage instead of powershell somehow bypasses the limit.

Great to here that, noted. I can apply it as well when needed. Thanks for sharing back your findings.
