### ISSUE TITLE
Disable MFC and UWP rounded corners

### ISSUE THREAD

**Issue by gailium119** [valinet/Win11DisableRoundedCorners#15]
For MFC apps and win32 apps,buttons and textboxes have rounded corners.
For UWP flyouts like the "restored Windows 10 network" , buttons have rounded corners.
Is there a way to fix this?

**Comment by valinet** [comment]
Each "problem" can be solved by addressing it at the root cause of it. There isn't a single master rounded corners on/off switch; this program patches the compositor and that has effect on top level windows only.

What's rounded because of the theme engine can be altered by modifying the theme or switching to another one, probably, taking care to disable the theme signing enforcement.

What's rounded because of the way certain controls are drawn in a particular framework can be addresses by patching how drawing is done in that particular framework, probably.

I haven't looked into any of the stuff mentioned by you, so I personally don't know how to do it.
