### ISSUE TITLE
Suggestion:

### ISSUE THREAD

**Issue by MihaiCristianCondrea** [valinet/Win11DisableRoundedCorners#20]
EN:
When Win10EnableRoundedCorners? XDDD By the way, I'm romanian too XD

**Comment by valinet** [comment]
Hi

Well, idk, it’s hard to implement something like that when not the actual owner of the code. After all, the Desktop Window Manager is still Microsoft’s product, I just took a brief look at its internals and was able to figure that much. As far as I know, window corner radius is not implemented at all in Windows 10, so something has to be built from scratch, and it’s not an easy task, besides not being able to work with the source, it’s also the thing that working on a compositor and doing things properly is not trivial.

So yeah, from my side, chances are slim to non-existant at the moment, I am not actively looking into it, just have no interest in it and also have a bunch of other stuff to take care of.

Anyway, maybe someone figures it out. I personally prefer Windows 11 due to various other things besides this; for the UI thingsI dislike, I wrote [ExplorerPatcher](https://github.com/valinet/ExplorerPatcher) which restores the sane UI from Windows 10.

Salutări și numai bine!
