### ISSUE TITLE
Rounded Corners are back!

### ISSUE THREAD

**Issue by Nirmal4G** [valinet/Win11DisableRoundedCorners#9]
With the latest cumulative update (**KB5006746**) bringing the Windows 11 build to 22000.282, the DWM file has been updated again and it lost all its sharp corner goodness!

This is the console output I'm getting:

```log
Unable to determine function address.
```

Can you please fix it?

**Comment by valinet** [comment]
Symbols are not available yet for 282. It will fix itself once the files are available from Microsoft. Until then, not much I can do.

**Comment by Nirmal4G** [comment]
Then, shouldn't the error say, "Debug symbols aren't available yet" or "Unable to download debug symbols for {build_version}"

**Comment by Wallace4444** [comment]
> Then, shouldn't the error say, "Debug symbols aren't available yet" or "Unable to download debug symbols for {build_version}"

Then fork the code and make the error code yourself champ. Jeez

**Comment by Nirmal4G** [comment]
@Wallace4444 Sure champ! 😏

As long as the author accepts PR for my suggestion. You shouldn't contribute without a proper conversation with the author.

> F.Y.I. Look at the last week's issue with .NET Foundation member tried to contribute and merge without discussing it with the maintainer. TLDR: She resigned from the board!

**Comment by valinet** [comment]
> 
> 
> @Wallace4444 Sure champ! 😏
> 
> As long as the author accepts PR for my suggestion. You shouldn't contribute without a proper conversation with the author.
> 
> > F.Y.I. Look at the last week's issue with .NET Foundation member tried to contribute and merge without discussing it with the maintainer. TLDR: She resigned from the board!

Uhm... no. I don't know about this .NETF saga, I am totally out of touch with that, I will look it up. But anyway, if I did not want people to make pull requests, I would have disabled that. I am not a huge corporation with billions of dollars cash and little purpose for them, so I don't have an army of people to watch over my repositories and engage in all kinds of small talk. I also have lots of other things to do daily other than managing these projects. If you find out something that is sensible and common sense better in the way you think about it, like this message here which is indeed, just a quality of life improvement which I did not have time for but definitely would make no harm, then yeah, making a PR directly is the way to go. What's there to talk? I am not stupid, I can easily understand that. No need for useless political corectness. My intent of these projects living on GitHub is that people learn from them and help me improve on them. That also involves people involving directly. That's also the reason I haven't even bothered to reply anymore... too many people ask for things that can be easily "fixed" if they invested 2 minutes of their life helping the person who helped them in the first place, instead of putting additional burden on him. I kind of align in sentiment with @Wallace4444's reply here.

And I'd say, even as a general rule, contributing to projects is fine. That's why they are developed in the open. If they don't want you to contribute, they'd adopt the Android model for example: although it is open source, it is not open - Google develops the next version behind closed doors, and then just publishes the source of the then previous version when they start working on the next one.

And btw, Microsoft made the symbols available, so this will work again. Idk why it took them a while, but whatever, now they're there.

**Comment by Nirmal4G** [comment]
@valinet I'm happy to contribute but its just good manners to ask for permission first! Sorry if I made you think I'm putting a lot on your shoulders.

**Comment by valinet** [comment]
@Nirmal4G no worries. Not you in particular, I was speaking in general. I receive a lot of messages and some if not most of them could easily be solved if people paid just that much more attention or decided to invest those 2 minutes… again, not something against you in particular. Thanks.
